# fly.toml app configuration file generated for remark42-floral-snow-1844 on 2024-12-18T15:52:17-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remark42-floral-snow-1844'
primary_region = 'bos'

[build]
  image = 'umputun/remark42:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = '10s'
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/web/"

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = "remark42_data"
  destination = "srv/var"
